/// Flutter icons CustomICons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomICons
///      fonts:
///       - asset: fonts/CustomICons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomICons {
  CustomICons._();

  static const _kFontFam = 'CustomICons';
  static const String? _kFontPkg = null;

  static const IconData quran__1_ = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
