// lib/screens/quran/constants/quran_constants.dart
class QuranConstants {
  // Default last read data
  static const Map<String, dynamic> defaultLastRead = {
    'surah_number': 1,
    'ayah_number': 1,
    'surah_name': 'Al-Fatihah',
    'arabic_name': 'الفَاتِحَة',
    'source': 'surah',
  };

  // Complete Surahs list - moved from widget to prevent recreation
  static const List<Map<String, String>> surahs = [
    {
      "name": "Al-Fatihah",
      "arabic": "الفَاتِحَة",
      "origin": "Meccan",
      "verses": "7",
    },
    {
      "name": "Al-Baqarah",
      "arabic": "البَقَرَة",
      "origin": "Medinan",
      "verses": "286",
    },
    {
      "name": "Aal-E-Imran",
      "arabic": "آلِ عِمرَان",
      "origin": "Medinan",
      "verses": "200",
    },
    {
      "name": "An-Nisa",
      "arabic": "النِّسَآء",
      "origin": "Medinan",
      "verses": "176",
    },
    {
      "name": "Al-Maidah",
      "arabic": "المَآئِدَة",
      "origin": "Medinan",
      "verses": "120",
    },
    {
      "name": "Al-Anam",
      "arabic": "الأَنعَام",
      "origin": "Meccan",
      "verses": "165",
    },
    {
      "name": "Al-Araf",
      "arabic": "الأَعرَاف",
      "origin": "Meccan",
      "verses": "206",
    },
    {
      "name": "Al-Anfal",
      "arabic": "الأَنفَال",
      "origin": "Medinan",
      "verses": "75",
    },
    {
      "name": "At-Tawbah",
      "arabic": "التَّوبَة",
      "origin": "Medinan",
      "verses": "129",
    },
    {"name": "Yunus", "arabic": "يُونُس", "origin": "Meccan", "verses": "109"},
    {"name": "Hud", "arabic": "هُود", "origin": "Meccan", "verses": "123"},
    {"name": "Yusuf", "arabic": "يُوسُف", "origin": "Meccan", "verses": "111"},
    {
      "name": "Ar-Rad",
      "arabic": "الرَّعد",
      "origin": "Medinan",
      "verses": "43",
    },
    {
      "name": "Ibrahim",
      "arabic": "إِبرَاهِيم",
      "origin": "Meccan",
      "verses": "52",
    },
    {"name": "Al-Hijr", "arabic": "الحِجر", "origin": "Meccan", "verses": "99"},
    {
      "name": "An-Nahl",
      "arabic": "النَّحل",
      "origin": "Meccan",
      "verses": "128",
    },
    {
      "name": "Al-Isra",
      "arabic": "الإِسرَآء",
      "origin": "Meccan",
      "verses": "111",
    },
    {
      "name": "Al-Kahf",
      "arabic": "الكَهف",
      "origin": "Meccan",
      "verses": "110",
    },
    {"name": "Maryam", "arabic": "مَريَم", "origin": "Meccan", "verses": "98"},
    {"name": "Taha", "arabic": "طه", "origin": "Meccan", "verses": "135"},
    {
      "name": "Al-Anbiya",
      "arabic": "الأَنبِيَآء",
      "origin": "Meccan",
      "verses": "112",
    },
    {"name": "Al-Hajj", "arabic": "الحَج", "origin": "Medinan", "verses": "78"},
    {
      "name": "Al-Muminun",
      "arabic": "المُؤمِنُون",
      "origin": "Meccan",
      "verses": "118",
    },
    {
      "name": "An-Nur",
      "arabic": "النُّور",
      "origin": "Medinan",
      "verses": "64",
    },
    {
      "name": "Al-Furqan",
      "arabic": "الفُرقَان",
      "origin": "Meccan",
      "verses": "77",
    },
    {
      "name": "Ash-Shuara",
      "arabic": "الشُّعَرَآء",
      "origin": "Meccan",
      "verses": "227",
    },
    {
      "name": "An-Naml",
      "arabic": "النَّمل",
      "origin": "Meccan",
      "verses": "93",
    },
    {
      "name": "Al-Qasas",
      "arabic": "القَصَص",
      "origin": "Meccan",
      "verses": "88",
    },
    {
      "name": "Al-Ankabut",
      "arabic": "العَنكَبُوت",
      "origin": "Meccan",
      "verses": "69",
    },
    {"name": "Ar-Rum", "arabic": "الرُّوم", "origin": "Meccan", "verses": "60"},
    {"name": "Luqman", "arabic": "لُقمَان", "origin": "Meccan", "verses": "34"},
    {
      "name": "As-Sajdah",
      "arabic": "السَّجدَة",
      "origin": "Meccan",
      "verses": "30",
    },
    {
      "name": "Al-Ahzab",
      "arabic": "الأَحزَاب",
      "origin": "Medinan",
      "verses": "73",
    },
    {"name": "Saba", "arabic": "سَبَأ", "origin": "Meccan", "verses": "54"},
    {"name": "Fatir", "arabic": "فَاطِر", "origin": "Meccan", "verses": "45"},
    {"name": "Ya-Sin", "arabic": "يس", "origin": "Meccan", "verses": "83"},
    {
      "name": "As-Saffat",
      "arabic": "الصَّافَّات",
      "origin": "Meccan",
      "verses": "182",
    },
    {"name": "Sad", "arabic": "ص", "origin": "Meccan", "verses": "88"},
    {
      "name": "Az-Zumar",
      "arabic": "الزُّمَر",
      "origin": "Meccan",
      "verses": "75",
    },
    {"name": "Ghafir", "arabic": "غَافِر", "origin": "Meccan", "verses": "85"},
    {
      "name": "Fussilat",
      "arabic": "فُصِّلَت",
      "origin": "Meccan",
      "verses": "54",
    },
    {
      "name": "Ash-Shuraa",
      "arabic": "الشُّورَى",
      "origin": "Meccan",
      "verses": "53",
    },
    {
      "name": "Az-Zukhruf",
      "arabic": "الزُّخرُف",
      "origin": "Meccan",
      "verses": "89",
    },
    {
      "name": "Ad-Dukhan",
      "arabic": "الدُّخَان",
      "origin": "Meccan",
      "verses": "59",
    },
    {
      "name": "Al-Jathiyah",
      "arabic": "الجَاثِيَة",
      "origin": "Meccan",
      "verses": "37",
    },
    {
      "name": "Al-Ahqaf",
      "arabic": "الأَحقَاف",
      "origin": "Meccan",
      "verses": "35",
    },
    {
      "name": "Muhammad",
      "arabic": "مُحَمَّد",
      "origin": "Medinan",
      "verses": "38",
    },
    {
      "name": "Al-Fath",
      "arabic": "الفَتح",
      "origin": "Medinan",
      "verses": "29",
    },
    {
      "name": "Al-Hujurat",
      "arabic": "الحُجُرَات",
      "origin": "Medinan",
      "verses": "18",
    },
    {"name": "Qaf", "arabic": "ق", "origin": "Meccan", "verses": "45"},
    {
      "name": "Adh-Dhariyat",
      "arabic": "الذَّارِيَات",
      "origin": "Meccan",
      "verses": "60",
    },
    {"name": "At-Tur", "arabic": "الطُّور", "origin": "Meccan", "verses": "49"},
    {
      "name": "An-Najm",
      "arabic": "النَّجم",
      "origin": "Meccan",
      "verses": "62",
    },
    {
      "name": "Al-Qamar",
      "arabic": "القَمَر",
      "origin": "Meccan",
      "verses": "55",
    },
    {
      "name": "Ar-Rahman",
      "arabic": "الرَّحمَن",
      "origin": "Medinan",
      "verses": "78",
    },
    {
      "name": "Al-Waqiah",
      "arabic": "الوَاقِعَة",
      "origin": "Meccan",
      "verses": "96",
    },
    {
      "name": "Al-Hadid",
      "arabic": "الحَدِيد",
      "origin": "Medinan",
      "verses": "29",
    },
    {
      "name": "Al-Mujadila",
      "arabic": "المُجَادلَة",
      "origin": "Medinan",
      "verses": "22",
    },
    {
      "name": "Al-Hashr",
      "arabic": "الحَشر",
      "origin": "Medinan",
      "verses": "24",
    },
    {
      "name": "Al-Mumtahanah",
      "arabic": "المُمتَحنَة",
      "origin": "Medinan",
      "verses": "13",
    },
    {"name": "As-Saf", "arabic": "الصَّف", "origin": "Medinan", "verses": "14"},
    {
      "name": "Al-Jumuah",
      "arabic": "الجُمُعَة",
      "origin": "Medinan",
      "verses": "11",
    },
    {
      "name": "Al-Munafiqun",
      "arabic": "المُنَافِقُون",
      "origin": "Medinan",
      "verses": "11",
    },
    {
      "name": "At-Taghabun",
      "arabic": "التَّغَابُن",
      "origin": "Medinan",
      "verses": "18",
    },
    {
      "name": "At-Talaq",
      "arabic": "الطَّلاَق",
      "origin": "Medinan",
      "verses": "12",
    },
    {
      "name": "At-Tahrim",
      "arabic": "التَّحرِيم",
      "origin": "Medinan",
      "verses": "12",
    },
    {"name": "Al-Mulk", "arabic": "المُلك", "origin": "Meccan", "verses": "30"},
    {
      "name": "Al-Qalam",
      "arabic": "القَلَم",
      "origin": "Meccan",
      "verses": "52",
    },
    {
      "name": "Al-Haqqah",
      "arabic": "الحَآقَّة",
      "origin": "Meccan",
      "verses": "52",
    },
    {
      "name": "Al-Maarij",
      "arabic": "المَعَارِج",
      "origin": "Meccan",
      "verses": "44",
    },
    {"name": "Nuh", "arabic": "نُوح", "origin": "Meccan", "verses": "28"},
    {"name": "Al-Jinn", "arabic": "الجِن", "origin": "Meccan", "verses": "28"},
    {
      "name": "Al-Muzzammil",
      "arabic": "المُزَّمِّل",
      "origin": "Meccan",
      "verses": "20",
    },
    {
      "name": "Al-Muddaththir",
      "arabic": "المُدَّثِّر",
      "origin": "Meccan",
      "verses": "56",
    },
    {
      "name": "Al-Qiyamah",
      "arabic": "القِيَامَة",
      "origin": "Meccan",
      "verses": "40",
    },
    {
      "name": "Al-Insan",
      "arabic": "الإِنسَان",
      "origin": "Medinan",
      "verses": "31",
    },
    {
      "name": "Al-Mursalat",
      "arabic": "المُرسَلاَت",
      "origin": "Meccan",
      "verses": "50",
    },
    {
      "name": "An-Naba",
      "arabic": "النَّبَإ",
      "origin": "Meccan",
      "verses": "40",
    },
    {
      "name": "An-Naziat",
      "arabic": "النَّازِعَات",
      "origin": "Meccan",
      "verses": "46",
    },
    {"name": "Abasa", "arabic": "عَبَسَ", "origin": "Meccan", "verses": "42"},
    {
      "name": "At-Takwir",
      "arabic": "التَّكوِير",
      "origin": "Meccan",
      "verses": "29",
    },
    {
      "name": "Al-Infitar",
      "arabic": "الإِنفِطَار",
      "origin": "Meccan",
      "verses": "19",
    },
    {
      "name": "Al-Mutaffifin",
      "arabic": "المُطَفِّفِين",
      "origin": "Meccan",
      "verses": "36",
    },
    {
      "name": "Al-Inshiqaq",
      "arabic": "الإِنشِقَاق",
      "origin": "Meccan",
      "verses": "25",
    },
    {
      "name": "Al-Buruj",
      "arabic": "البُرُوج",
      "origin": "Meccan",
      "verses": "22",
    },
    {
      "name": "At-Tariq",
      "arabic": "الطَّارِق",
      "origin": "Meccan",
      "verses": "17",
    },
    {
      "name": "Al-Ala",
      "arabic": "الأَعلَى",
      "origin": "Meccan",
      "verses": "19",
    },
    {
      "name": "Al-Ghashiyah",
      "arabic": "الغَاشِيَة",
      "origin": "Meccan",
      "verses": "26",
    },
    {"name": "Al-Fajr", "arabic": "الفَجر", "origin": "Meccan", "verses": "30"},
    {
      "name": "Al-Balad",
      "arabic": "البَلَد",
      "origin": "Meccan",
      "verses": "20",
    },
    {
      "name": "Ash-Shams",
      "arabic": "الشَّمس",
      "origin": "Meccan",
      "verses": "15",
    },
    {
      "name": "Al-Layl",
      "arabic": "اللَّيل",
      "origin": "Meccan",
      "verses": "21",
    },
    {
      "name": "Ad-Duhaa",
      "arabic": "الضُّحَى",
      "origin": "Meccan",
      "verses": "11",
    },
    {
      "name": "Ash-Sharh",
      "arabic": "الشَّرح",
      "origin": "Meccan",
      "verses": "8",
    },
    {"name": "At-Tin", "arabic": "التِّين", "origin": "Meccan", "verses": "8"},
    {
      "name": "Al-Alaq",
      "arabic": "العَلَق",
      "origin": "Meccan",
      "verses": "19",
    },
    {"name": "Al-Qadr", "arabic": "القَدر", "origin": "Meccan", "verses": "5"},
    {
      "name": "Al-Bayyinah",
      "arabic": "البَيِّنَة",
      "origin": "Medinan",
      "verses": "8",
    },
    {
      "name": "Az-Zalzalah",
      "arabic": "الزَّلزَلَة",
      "origin": "Medinan",
      "verses": "8",
    },
    {
      "name": "Al-Adiyat",
      "arabic": "العَادِيات",
      "origin": "Meccan",
      "verses": "11",
    },
    {
      "name": "Al-Qariah",
      "arabic": "القَارِعَة",
      "origin": "Meccan",
      "verses": "11",
    },
    {
      "name": "At-Takathur",
      "arabic": "التَّكَاثُر",
      "origin": "Meccan",
      "verses": "8",
    },
    {"name": "Al-Asr", "arabic": "العَصر", "origin": "Meccan", "verses": "3"},
    {
      "name": "Al-Humazah",
      "arabic": "الهُمَزَة",
      "origin": "Meccan",
      "verses": "9",
    },
    {"name": "Al-Fil", "arabic": "الفِيل", "origin": "Meccan", "verses": "5"},
    {"name": "Quraysh", "arabic": "قُرَيش", "origin": "Meccan", "verses": "4"},
    {
      "name": "Al-Maun",
      "arabic": "المَاعُون",
      "origin": "Meccan",
      "verses": "7",
    },
    {
      "name": "Al-Kawthar",
      "arabic": "الكَوثَر",
      "origin": "Meccan",
      "verses": "3",
    },
    {
      "name": "Al-Kafirun",
      "arabic": "الكَافِرُون",
      "origin": "Meccan",
      "verses": "6",
    },
    {
      "name": "An-Nasr",
      "arabic": "النَّصر",
      "origin": "Medinan",
      "verses": "3",
    },
    {
      "name": "Al-Masad",
      "arabic": "المَسَد",
      "origin": "Meccan",
      "verses": "5",
    },
    {
      "name": "Al-Ikhlas",
      "arabic": "الإِخلاَص",
      "origin": "Meccan",
      "verses": "4",
    },
    {
      "name": "Al-Falaq",
      "arabic": "الفَلَق",
      "origin": "Meccan",
      "verses": "5",
    },
    {"name": "An-Nas", "arabic": "النَّاس", "origin": "Meccan", "verses": "6"},
  ];

  // Complete Parahs list - moved from widget to prevent recreation
  static const List<Map<String, String>> parahs = [
    {"arabic": "الٓمِٓ", "verses": "148", "english": "Alif Lam Meem"},
    {"arabic": "سَيَقُولُ", "verses": "111", "english": "Sayaqool"},
    {"arabic": "تِلْكَ الرُّسُلُ", "verses": "126", "english": "Tilkal Rusulu"},
    {
      "arabic": "لَنْ تَنَالُوا الْبِرَّ",
      "verses": "131",
      "english": "Lan Tana loo Al-Birra",
    },
    {"arabic": "وَالْمُحْصَنَاتُ", "verses": "124", "english": "Wal Mohsanat"},
    {
      "arabic": "لَا يُحِبُّ اللَّهُ",
      "verses": "110",
      "english": "La Yuhibbullah",
    },
    {"arabic": "وَإِذَا سَمِعُوا", "verses": "149", "english": "Wa Iza Samiu"},
    {"arabic": "وَلَوْ أَنَّنَا", "verses": "142", "english": "Wa Lau Annana"},
    {"arabic": "قَالَلْمَلَأُ", "verses": "159", "english": "Qalal Malao"},
    {"arabic": "وَاعْلَمُوا", "verses": "127", "english": "Wa A'lamu"},
    {"arabic": "يَعْتَذِرُونَ", "verses": "151", "english": "Yatazeroon"},
    {
      "arabic": "وَمَا مِن دَآبَّةٍ",
      "verses": "170",
      "english": "Wa Mamin Daabat",
    },
    {"arabic": "وَمَا أُبَرِّئُ", "verses": "154", "english": "Wa Ma Ubrioo"},
    {"arabic": "رُبَمَا", "verses": "227", "english": "Rubama"},
    {
      "arabic": "سُبْحَانَ الَّذِي",
      "verses": "185",
      "english": "Subhan Alladhi",
    },
    {"arabic": "قَالَ أَلَمْ", "verses": "269", "english": "Qala Alam"},
    {
      "arabic": "اقْتَرَبَ لِلْنَّاسِ",
      "verses": "190",
      "english": "Iqtaraba Lin-Nasi",
    },
    {"arabic": "قَدْ أَفْلَحَ", "verses": "202", "english": "Qadd Aflaha"},
    {
      "arabic": "وَقَالَ الَّذِينَ",
      "verses": "339",
      "english": "Wa Qalallazina",
    },
    {"arabic": "أَمَّنْ خَلَقَ", "verses": "171", "english": "A’man Khalaq"},
    {
      "arabic": "أُتْلُ مَاأُوْحِيَ",
      "verses": "178",
      "english": "Utlu Ma Oohi",
    },
    {"arabic": "وَمَنْ يَّقْنُتْ", "verses": "169", "english": "Wa Man Yaqnut"},
    {"arabic": "وَمَآ لِيَ", "verses": "357", "english": "Wa Mali"},
    {"arabic": "فَمَنْ أَظْلَمُ", "verses": "175", "english": "Faman Azlamu"},
    {
      "arabic": "إِلَيْهِ يُرَدُّ",
      "verses": "246",
      "english": "Ilayhi Yuruddo",
    },
    {"arabic": "حَــــم", "verses": "195", "english": "Ha Meem"},
    {
      "arabic": "قَالَ فَمَا خَطْبُكُم",
      "verses": "399",
      "english": "Qala Fama Khatbukum",
    },
    {
      "arabic": "قَدْ سَمِعَ اللَّهُ",
      "verses": "137",
      "english": "Qadd Sami Allah",
    },
    {
      "arabic": "تَبَارَكَ الَّذِي",
      "verses": "431",
      "english": "Tabarakallazi",
    },
    {
      "arabic": "عَمَّ يَتَسَاءَلُونَ",
      "verses": "564",
      "english": "Amma Yatasa’aloon",
    },
  ];
}
